name: "magicport"
networks:
  magicport:
    name: magicport

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
#      - npmnx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/be:/var/www/html/be:delegated
    networks:
      - magicport

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src/be:/var/www/html/be:delegated
#    secrets:
#      - db_connection
#      - db_host
#      - db_port
#      - db_database
#      - db_username
#      - db_password
#    environment:
#      - DB_CONNECTION_FILE=/run/secrets/db_connection
#      - DB_HOST_FILE=/run/secrets/db_host
#      - DB_PORT_FILE=/run/secrets/db_port
#      - DB_DATABASE_FILE=/run/secrets/db_database
#      - DB_USERNAME_FILE=/run/secrets/db_username
#      - DB_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - magicport

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src/be:/var/www/html/be
    working_dir: /var/www/html/be
    networks:
      - magicport

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src/be:/var/www/html/be
    working_dir: /var/www/html/be
    entrypoint: ["php", "artisan"]
    networks:
      - magicport

  phpunit:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: phpunit
    volumes:
      - ./src/be:/var/www/html/be
    working_dir: /var/www/html/be
    entrypoint: ["/var/www/html/be/vendor/bin/phpunit"]
    networks:
      - magicport

  mysql:
    image: mysql:9.0.1
    container_name: mysql
    ports:
      - 4306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - magicport
    environment:
      - MYSQL_DATABASE=project_development
      - MYSQL_USER=magicport
      - MYSQL_PASSWORD=magicport
      - MYSQL_ROOT_PASSWORD=magicport
#    secrets:
#      - db_database
#      - db_username
#      - db_password
#      - db_root_password
#    environment:
#      - MYSQL_DATABASE_FILE=/run/secrets/db_database
#      - MYSQL_USER_FILE=/run/secrets/db_username
#      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
#      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
#
#  npmnx:
#    build:
#      context: .
#      dockerfile: node.dockerfile
#    container_name: npmnx
#    ports:
#      - 3000:3000
#    working_dir: /var/www/html/fe
#    networks:
#      - magicport
#
#  npm:
#    image: node:current-alpine
#    container_name: npm
#    ports:
#      - 5173:3000
#    volumes:
#      - ./src/fe:/var/www/html/fe
#    working_dir: /var/www/html/fe
#    entrypoint: ["npm"]
#    networks:
#      - magicport
#
#  npx:
#    image: node:current-alpine
#    container_name: npx
#    volumes:
#      - ./src/fe:/var/www/html/fe
#    working_dir: /var/www/html/fe
#    entrypoint: ["npx"]
#    networks:
#      - magicport

#  redis:
#    image: redis:alpine
#    container_name: redis
#    command: redis-server --save 20 1 --loglevel warning
#    ports:
#      - "8002:6379"
#    volumes:
#      - ./db/redis:/data

#secrets:
#  db_connection:
#    file: ./secrets/db_connection
#  db_host:
#    file: ./secrets/db_host
#  db_port:
#    file: ./secrets/db_port
#  db_database:
#    file: ./secrets/db_database
#  db_username:
#    file: ./secrets/db_username
#  db_password:
#    file: ./secrets/db_password
#  db_root_password:
#    file: ./secrets/db_root_password
#  app_key:
#    file: ./secrets/app_key